"""initial tables

Revision ID: 050264b5e243
Revises:
Create Date: 2026-09-02 09:46:17.815210+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from app.database.types import UUIDType

revision = "050264b5e243"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_type", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("content_mode", sa.String(length=32), nullable=False),
        sa.Column("daily_ayah", sa.Boolean(), nullable=False),
        sa.Column("daily_time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("daily_type", sa.String(length=10), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_daily_sent_date", sa.Date(), nullable=True),
        sa.Column("uuid", UUIDType(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_chats")),
    )
    op.create_index(op.f("ix_chats_chat_id"), "chats", ["chat_id"], unique=True)
    op.create_table(
        "sent_history",
        sa.Column("chat_uuid", UUIDType(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("AYAH", "PAGE", name="readingmode", native_enum=False, length=5),
            nullable=False,
        ),
        sa.Column("ayah_uuid", UUIDType(), nullable=False),
        sa.Column("uuid", UUIDType(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_uuid"],
            ["chats.uuid"],
            name=op.f("fk_sent_history_chat_uuid_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_sent_history")),
    )
    op.create_index(
        op.f("ix_sent_history_chat_uuid"), "sent_history", ["chat_uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sent_history_chat_uuid"), table_name="sent_history")
    op.drop_table("sent_history")
    op.drop_index(op.f("ix_chats_chat_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
